import os
import glob

# --- إعدادات الموقع ---
BASE_URL = "https://aqarnasr.netlify.app"
# ✨ سنقرأ من مجلد _site ونكتب فيه مباشرة
SITE_DIR = "_site"
SITEMAP_FILE = os.path.join(SITE_DIR, "sitemap.xml")

def generate_xml():
    print("🚀 Starting Final Sitemap Generation (from _site)...")

    if not os.path.isdir(SITE_DIR):
        print(f"❌ Error: Build directory '{SITE_DIR}' not found. Run Jekyll build first.")
        return

    xml_content = '<?xml version="1.0" encoding="UTF-8"?>\n'
    xml_content += '<!-- GENERATED BY FINAL PYTHON SCRIPT -->\n'
    xml_content += '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n'

    # 1. البحث عن كل صفحات HTML في الموقع المبني
    # هذا يضمن إضافة كل الصفحات الثابتة والديناميكية التي أنشأها Jekyll
    search_path_html = os.path.join(SITE_DIR, '**', '*.html')
    static_pages_found = 0
    for filepath in glob.glob(search_path_html, recursive=True):
        # تجاهل الصفحات التي لا نريدها في الخريطة
        if "404.html" in filepath:
            continue

        # تحويل مسار الملف إلى رابط URL
        relative_path = os.path.relpath(filepath, SITE_DIR)
        # إزالة 'index.html' لجعل الرابط نظيفًا
        if os.path.basename(relative_path) == 'index.html':
            relative_path = os.path.dirname(relative_path)
        
        # إزالة امتداد .html
        url_part = relative_path.replace('\\', '/').replace('.html', '')
        
        # تجنب الروابط المكررة للصفحة الرئيسية
        if url_part == ".":
            url_part = ""
            
        full_url = f"{BASE_URL}/{url_part}"
        
        # تجاهل روابط تفاصيل العقارات والطلبات لأننا سنضيفها بشكل منفصل
        if 'details.html' in full_url or 'request-details.html' in full_url:
            continue

        xml_content += f'  <url><loc>{full_url}</loc><priority>0.9</priority></url>\n'
        static_pages_found += 1

    # 2. العقارات (Properties) - من ملفات JSON في _site
    search_path_props = os.path.join(SITE_DIR, 'data', 'properties', '**', '*.json')
    properties_found = 0
    for filepath in glob.glob(search_path_props, recursive=True):
        if "index.json" in os.path.basename(filepath): continue
        
        clean_id = os.path.basename(filepath).replace('.json', '')
        category = os.path.basename(os.path.dirname(filepath))
        
        full_url = f"{BASE_URL}/details.html?id={clean_id}&amp;category={category}"
        xml_content += f'  <url><loc>{full_url}</loc><priority>0.8</priority></url>\n'
        properties_found += 1

    # 3. الطلبات (Requests) - من ملفات JSON في _site
    search_path_reqs = os.path.join(SITE_DIR, 'data', 'requests', '**', '*.json')
    requests_found = 0
    for filepath in glob.glob(search_path_reqs, recursive=True):
        if "index.json" in os.path.basename(filepath): continue

        clean_id = os.path.basename(filepath).replace('.json', '')
        category = os.path.basename(os.path.dirname(filepath))

        full_url = f"{BASE_URL}/request-details.html?id={clean_id}&amp;category={category}"
        xml_content += f'  <url><loc>{full_url}</loc><priority>0.6</priority></url>\n'
        requests_found += 1

    xml_content += '</urlset>'
    
    with open(SITEMAP_FILE, "w", encoding="utf-8") as f:
        f.write(xml_content)
    
    print(f"\n--- Sitemap Summary ---")
    print(f"HTML Pages Found: {static_pages_found}")
    print(f"Properties Found: {properties_found}")
    print(f"Requests Found: {requests_found}")
    print(f"Total URLs Generated: {static_pages_found + properties_found + requests_found}")
    print(f"✅ Sitemap successfully written to: {SITEMAP_FILE}")

if __name__ == "__main__":
    generate_xml()
