import os
import glob

# إعدادات الموقع
BASE_URL = "https://aqarnasr.netlify.app"
OUTPUT_DIR = "_site"
SITEMAP_FILE = os.path.join(OUTPUT_DIR, "sitemap.xml")

def generate_xml():
    # التأكد من أن مجلد النشر موجود (لأننا سنعمل بعد بناء جيكل)
    if not os.path.exists(OUTPUT_DIR):
        os.makedirs(OUTPUT_DIR)

    print("🚀 Starting Custom Sitemap Generation...")

    xml_content = '<?xml version="1.0" encoding="UTF-8"?>\n'
    # هذا التعليق سيؤكد لك أن الملف هو ملفنا الجديد
    xml_content += '<!-- GENERATED BY CUSTOM PYTHON SCRIPT -->\n'
    xml_content += '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n'

    # 1. الصفحات الرئيسية الثابتة
    static_pages = ["", "properties-filtered", "requests-filtered", "add-your-property", "contact-us", "about-us"]
    for page in static_pages:
        xml_content += f'  <url><loc>{BASE_URL}/{page}</loc><priority>1.0</priority></url>\n'

    # 2. العقارات (Properties)
    # نبحث في مجلد البيانات الأصلي
    for filepath in glob.glob("data/properties/*/*.json"):
        if "index.json" in filepath: continue
        
        filename = os.path.basename(filepath)
        clean_id = filename.replace('.json', '')
        category = os.path.basename(os.path.dirname(filepath))
        
        # الرابط الديناميكي
        full_url = f"{BASE_URL}/details.html?id={clean_id}&amp;category={category}"
        xml_content += f'  <url><loc>{full_url}</loc><priority>0.8</priority></url>\n'

    # 3. الطلبات (Requests)
    for filepath in glob.glob("data/requests/*/*.json"):
        if "index.json" in filepath: continue
        
        filename = os.path.basename(filepath)
        clean_id = filename.replace('.json', '')
        category = os.path.basename(os.path.dirname(filepath))
        
        full_url = f"{BASE_URL}/request-details.html?id={clean_id}&amp;category={category}"
        xml_content += f'  <url><loc>{full_url}</loc><priority>0.6</priority></url>\n'

    xml_content += '</urlset>'
    
    # الكتابة في المجلد النهائي
    with open(SITEMAP_FILE, "w", encoding="utf-8") as f:
        f.write(xml_content)
    
    print(f"✅ Sitemap written to: {SITEMAP_FILE}")

if __name__ == "__main__":
    generate_xml()
