import os
import glob

BASE_URL = "https://aqarnasr.netlify.app"
SITEMAP_FILE = "sitemap.xml"

def generate_xml():
    print("🚀 Starting Final Sitemap Generation...")
    urls = set()

    # 1. الصفحات الثابتة
    static_pages = [
        "", "properties-filtered.html", "requests-filtered.html",
        "add-your-property.html", "contact-us.html", "about-us.html", "privacy-policy.html"
    ]
    for page in static_pages:
        urls.add(f"{BASE_URL}/{page}")

    # 2. العقارات (Properties)
    search_path_props = os.path.join('data', 'properties', '**', '*.json')
    properties_found = 0
    for filepath in glob.glob(search_path_props, recursive=True):
        if "index.json" in os.path.basename(filepath): continue
        clean_id = os.path.basename(filepath).replace('.json', '')
        category = os.path.basename(os.path.dirname(filepath))
        if category and category != 'properties':
            urls.add(f"{BASE_URL}/details.html?id={clean_id}&amp;category={category}")
            properties_found += 1

    # 3. الطلبات (Requests)
    search_path_reqs = os.path.join('data', 'requests', '**', '*.json')
    requests_found = 0
    for filepath in glob.glob(search_path_reqs, recursive=True):
        if "index.json" in os.path.basename(filepath): continue
        clean_id = os.path.basename(filepath).replace('.json', '')
        category = os.path.basename(os.path.dirname(filepath))
        if category and category != 'requests':
            urls.add(f"{BASE_URL}/request-details.html?id={clean_id}&amp;category={category}")
            requests_found += 1

    # بناء محتوى XML
    xml_content = '<?xml version="1.0" encoding="UTF-8"?>\n'
    xml_content += '<!-- ✅ GENERATED BY THE CORRECT CUSTOM SCRIPT -->\n'
    xml_content += '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n'
    for url in sorted(list(urls)):
        xml_content += f'  <url><loc>{url}</loc></url>\n'
    xml_content += '</urlset>'
    
    with open(SITEMAP_FILE, "w", encoding="utf-8") as f:
        f.write(xml_content)
    
    print("\n--- Sitemap Summary ---")
    print(f"Static Pages: {len(static_pages)}")
    print(f"Properties Found: {properties_found}")
    print(f"Requests Found: {requests_found}")
    print(f"Total Unique URLs: {len(urls)}")
    print(f"✅ Sitemap written to: {SITEMAP_FILE}")

if __name__ == "__main__":
    generate_xml()
