name: Generate Apartments Data File

on:
  push:
    paths:
      - '_data/apartments-source/**' # سنضع المصادر هنا
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  generate_apartments_json:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Aggregate apartment data
        run: |
          # سنستخدم أداة jq لتجميع كل ملفات JSON في ملف واحد
          jq -s '.' _data/apartments-source/*.json > _data/apartments.json

      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "github-actions-bot@users.noreply.github.com"
          git add _data/apartments.json
          if git diff --cached --quiet; then
            echo "_data/apartments.json is up-to-date."
          else
            git commit -m "تحديث تلقائي لملف بيانات الشقق"
            git push
          fi
