name: Generate Category Index Files

on:
  push:
    paths:
      - '_data/properties/**' # <-- تم التحديث هنا
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  generate_index:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Generate index.json for each category
        run: |
          for dir in _data/properties/*/ ; do # <-- تم التحديث هنا
            if [ -d "$dir" ]; then
              category_path="${dir%/}"
              echo "Processing category: $category_path"
              
              echo "[" > "$category_path/index.json"
              
              first=true
              find "$category_path" -maxdepth 1 -type f -name '*.json' ! -name 'index.json' | while read -r file; do
                if [ "$first" = true ]; then
                  first=false
                else
                  echo "," >> "$category_path/index.json"
                fi
                jq -c . "$file" | tr -d '\n' >> "$category_path/index.json"
              done
              
              echo "" >> "$category_path/index.json"
              echo "]" >> "$category_path/index.json"
              
              echo "✅ Generated index.json in $category_path"
            fi
          done

      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "github-actions-bot@users.noreply.github.com"
          git add _data/properties/*/index.json # <-- تم التحديث هنا
          if git diff --cached --quiet; then
            echo "All index.json files are up-to-date."
          else
            git commit -m "توليد تلقائي لملفات index.json في _data"
            git push
          fi
